In [1]:
import pandas as pd

MA1 = pd.DataFrame()
for chunk in pd.read_csv("../ssd_data/combined_by_diskmodel/combined_MA1.csv", chunksize=1000000):
    MA1 = pd.concat([MA1, chunk], ignore_index=True)
MA1

,index,disk_id,ds,model,n_1,r_1,n_5,r_5,n_9,r_9,...,n_233,n_241,r_241,n_242,r_242,r_244,n_175,r_175,n_232,label
0,45,10045,20190101,MA1,130.0,4.294967e+09,97.0,0.0,100.0,38288.0,...,NaN,NaN,NaN,NaN,NaN,NaN,100.0,9.752124e+11,NaN,0
1,50,10048,20190101,MA1,130.0,4.294967e+09,96.0,0.0,100.0,38288.0,...,NaN,NaN,NaN,NaN,NaN,NaN,100.0,9.752134e+11,NaN,0
2,69,10066,20190101,MA1,130.0,4.294967e+09,96.0,0.0,100.0,46396.0,...,NaN,NaN,NaN,NaN,NaN,NaN,100.0,1.185723e+12,NaN,0
3,86,10083,20190101,MA1,130.0,4.294967e+09,98.0,0.0,100.0,39978.0,...,NaN,NaN,NaN,NaN,NaN,NaN,100.0,1.014085e+12,NaN,0
4,129,10122,20190101,MA1,130.0,4.294967e+09,97.0,0.0,100.0,45592.0,...,NaN,NaN,NaN,NaN,NaN,NaN,100.0,1.151518e+12,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4744310,11267559,9838,20190630,MA1,130.0,4.294967e+09,97.0,0.0,100.0,43197.0,...,NaN,NaN,NaN,NaN,NaN,NaN,100.0,1.086756e+12,NaN,0
4744311,11267567,9842,20190630,MA1,130.0,5.896511e+06,98.0,0.0,100.0,42705.0,...,NaN,NaN,NaN,NaN,NaN,NaN,100.0,1.078410e+12,NaN,0
4744312,11267600,9878,20190630,MA1,130.0,4.294967e+09,96.0,0.0,100.0,41465.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.048160e+12,NaN,0
4744313,11267700,9970,20190630,MA1,130.0,4.294967e+09,96.0,0.0,100.0,46623.0,...,NaN,NaN,NaN,NaN,NaN,NaN,100.0,1.164486e+12,NaN,0
4744314,11267707,9974,20190630,MA1,130.0,4.294967e+09,96.0,0.0,100.0,46623.0,...,NaN,NaN,NaN,NaN,NaN,NaN,100.0,1.164486e+12,NaN,0

In [2]:
del(MA1['index'])

In [3]:
# null값이 있는 열을 제거하는 코드
def remove_null_columns(df):
    # null인 컬럼을 확인하고, 모든 값이 null인 컬럼을 찾습니다.
    null_columns = df.columns[df.isnull().all()]
    
    # 모든 값이 null인 컬럼을 DataFrame에서 제거합니다.
    df = df.drop(null_columns, axis=1)
    
    return df

In [4]:
# 하나의 unique한 값으로만 이루어진 컬럼을 제거하는 코드
def remove_single_value_columns(df):
    single_value_cols = []
    for col in df.columns:
        unique_values = df[col].nunique()
        if unique_values == 1:
            single_value_cols.append(col)

    df_filtered = df.drop(single_value_cols, axis=1)
    return df_filtered

In [5]:
MA1 = remove_null_columns(MA1)
MA1 = remove_single_value_columns(MA1)

In [6]:
MA1=MA1.fillna(0)

In [16]:
MA1[MA1['label'] == 1]

,disk_id,ds,r_1,n_5,r_5,r_9,r_12,n_171,r_171,n_172,...,r_194,r_195,n_196,r_196,r_197,r_198,r_199,n_175,r_175,label
55019,3401,20190102,4.294967e+09,98.0,0.0,40012.0,59.0,100.0,0.0,100.0,...,16.0,2.260676e+09,100.0,0.0,0.0,0.0,0.0,100.0,1.005077e+12,1
55936,23729,20190102,4.294967e+09,98.0,2.0,40175.0,28.0,100.0,4.0,100.0,...,20.0,1.067805e+09,99.0,2.0,0.0,0.0,0.0,100.0,1.018337e+12,1
70405,41793,20190103,4.294967e+09,98.0,0.0,36522.0,28.0,100.0,0.0,100.0,...,14.0,2.791970e+08,100.0,0.0,0.0,0.0,0.0,100.0,9.280304e+11,1
75070,30146,20190103,4.294967e+09,98.0,0.0,36922.0,30.0,100.0,0.0,100.0,...,18.0,1.591232e+09,100.0,0.0,0.0,0.0,0.0,100.0,9.407059e+11,1
106266,37927,20190104,4.294967e+09,94.0,141.0,37481.0,30.0,99.0,70.0,100.0,...,8.0,2.748596e+09,97.0,141.0,0.0,0.0,0.0,100.0,9.497040e+11,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4132300,33445,20190603,4.294967e+09,96.0,0.0,44625.0,36.0,100.0,0.0,100.0,...,15.0,1.270160e+06,100.0,0.0,0.0,0.0,0.0,1.0,1.134050e+12,1
4175174,1230,20190605,4.294967e+09,98.0,0.0,44244.0,27.0,100.0,0.0,100.0,...,19.0,2.581993e+09,100.0,0.0,0.0,0.0,0.0,100.0,1.125316e+12,1
4178901,34874,20190605,4.294967e+09,98.0,0.0,40585.0,28.0,100.0,0.0,100.0,...,15.0,1.579518e+09,100.0,0.0,0.0,0.0,0.0,100.0,1.035432e+12,1
4182969,31327,20190606,4.294967e+09,98.0,0.0,42078.0,44.0,100.0,0.0,100.0,...,17.0,3.873290e+09,100.0,0.0,0.0,0.0,0.0,100.0,1.057160e+12,1
4195779,38773,20190606,4.294967e+09,98.0,2.0,44298.0,37.0,100.0,2.0,100.0,...,16.0,1.970826e+09,99.0,2.0,0.0,0.0,0.0,100.0,1.121018e+12,1

In [7]:
# 라벨이 1인 행을 필터링합니다.
selected_disk_model_1 = MA1[MA1['label'] == 1]

# 모델, disk_id, 그리고 날짜 순으로 정렬합니다.
selected_disk_model_1 = selected_disk_model_1.sort_values(by=['disk_id', 'ds'])

# disk_id와 model 열만을 선택하여 새로운 데이터 프레임에 저장합니다.
selected_disk_model_1 = selected_disk_model_1[['disk_id']].drop_duplicates().reset_index(drop=True)

# 결과 데이터 프레임을 출력합니다.
selected_disk_model_1

     disk_id
0        520
1       1156
2       1224
3       1225
4       1230
..       ...
270    42763
271    42764
272    42767
273    42815
274    42824

[275 rows x 1 columns]

In [10]:
# ds 컬럼에 따라 정렬
MA1 = MA1.sort_values(['disk_id', 'ds'])
# 결과 출력
MA1

,disk_id,ds,r_1,n_5,r_5,r_9,r_12,n_171,r_171,n_172,...,r_194,r_195,n_196,r_196,r_197,r_198,r_199,n_175,r_175,label
717975,12,20190126,1.745309e+09,98.0,0.0,39291.0,60.0,100.0,0.0,100.0,...,12.0,428404580.0,100.0,0.0,0.0,0.0,0.0,100.0,9.835897e+11,0
741568,12,20190127,3.620582e+09,98.0,0.0,39315.0,60.0,100.0,0.0,100.0,...,11.0,428404582.0,100.0,0.0,0.0,0.0,0.0,100.0,9.836836e+11,0
755075,12,20190128,4.294967e+09,98.0,0.0,39339.0,60.0,100.0,0.0,100.0,...,11.0,428404583.0,100.0,0.0,0.0,0.0,0.0,100.0,9.837775e+11,0
793248,12,20190129,4.294967e+09,98.0,0.0,39362.0,60.0,100.0,0.0,100.0,...,12.0,428404584.0,100.0,0.0,0.0,0.0,0.0,100.0,9.838715e+11,0
830717,12,20190130,4.294967e+09,98.0,0.0,39386.0,60.0,100.0,0.0,100.0,...,11.0,428404586.0,100.0,0.0,0.0,0.0,0.0,100.0,9.839654e+11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4628684,43297,20190626,2.706945e+09,93.0,0.0,50774.0,32.0,100.0,0.0,100.0,...,17.0,517500.0,100.0,0.0,0.0,0.0,0.0,100.0,1.279911e+12,0
4665712,43297,20190627,2.731255e+09,93.0,0.0,50796.0,32.0,100.0,0.0,100.0,...,17.0,517500.0,100.0,0.0,0.0,0.0,0.0,100.0,1.279996e+12,0
4685287,43297,20190628,2.756229e+09,93.0,0.0,50820.0,32.0,100.0,0.0,100.0,...,17.0,517500.0,100.0,0.0,0.0,0.0,0.0,100.0,1.280090e+12,0
4703761,43297,20190629,2.781762e+09,93.0,0.0,50844.0,32.0,100.0,0.0,100.0,...,17.0,517500.0,100.0,0.0,0.0,0.0,0.0,100.0,1.280184e+12,0
4723392,43297,20190630,2.807087e+09,93.0,0.0,50867.0,32.0,100.0,0.0,100.0,...,17.0,517500.0,100.0,0.0,0.0,0.0,0.0,100.0,1.280278e+12,0

In [21]:
extracted_disk_failure_model_all = pd.merge(selected_disk_model_1, MA1, on='disk_id', how='inner')

In [22]:
extracted_disk_failure_model_all

,disk_id,ds,r_1,n_5,r_5,r_9,r_12,n_171,r_171,n_172,...,r_194,r_195,n_196,r_196,r_197,r_198,r_199,n_175,r_175,label
0,520,20190130,9.376596e+08,96.0,0.0,38191.0,27.0,100.0,0.0,100.0,...,16.0,33733630.0,100.0,0.0,0.0,0.0,0.0,100.0,9.793172e+11,0
1,520,20190131,1.624577e+09,96.0,0.0,38215.0,27.0,100.0,0.0,100.0,...,17.0,33733726.0,100.0,0.0,0.0,0.0,0.0,100.0,9.794111e+11,0
2,520,20190201,2.014090e+09,96.0,0.0,38239.0,27.0,100.0,0.0,100.0,...,17.0,33733759.0,100.0,0.0,0.0,0.0,0.0,100.0,9.795051e+11,0
3,520,20190202,2.812968e+09,96.0,0.0,38263.0,27.0,100.0,0.0,100.0,...,16.0,33733774.0,100.0,0.0,0.0,0.0,0.0,100.0,9.795990e+11,0
4,520,20190203,3.442008e+09,96.0,0.0,38287.0,27.0,100.0,0.0,100.0,...,15.0,33733798.0,100.0,0.0,0.0,0.0,0.0,100.0,9.796929e+11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35210,42824,20190626,4.294967e+09,94.0,0.0,48860.0,46.0,100.0,0.0,100.0,...,17.0,884843672.0,100.0,0.0,0.0,0.0,0.0,100.0,1.241470e+12,0
35211,42824,20190627,4.294967e+09,94.0,0.0,48884.0,46.0,100.0,0.0,100.0,...,17.0,884886553.0,100.0,0.0,0.0,0.0,0.0,100.0,1.241564e+12,0
35212,42824,20190628,4.294967e+09,94.0,0.0,48908.0,46.0,100.0,0.0,100.0,...,18.0,884924703.0,100.0,0.0,0.0,0.0,0.0,100.0,1.241658e+12,0
35213,42824,20190629,4.294967e+09,94.0,0.0,48932.0,46.0,100.0,0.0,100.0,...,18.0,884965991.0,100.0,0.0,0.0,0.0,0.0,100.0,1.241751e+12,0
35214,42824,20190630,4.294967e+09,94.0,0.0,48955.0,46.0,100.0,0.0,100.0,...,18.0,885006704.0,100.0,0.0,0.0,0.0,0.0,100.0,1.241845e+12,0

In [11]:
MA1['label'].value_counts()

label
0    4744040
1        275
Name: count, dtype: int64

In [12]:
# label이 1인 행의 인덱스 찾기
label_index = MA1[extracted_disk_failure_model_all['label'] == 1].index[0]

# 조건에 맞는 행 인덱스 선택
rows_to_label = MA1.iloc[label_index-29:label_index+1]

# disk_id가 변경된 행의 인덱스 찾기
disk_id_changed_index = rows_to_label[rows_to_label['disk_id'].diff() != 0].index

# 변경된 행을 제외하고 label을 1로 변경
rows_to_label.loc[~rows_to_label.index.isin(disk_id_changed_index), 'label'] = 1

In [13]:
rows_to_label

,disk_id,ds,r_1,n_5,r_5,r_9,r_12,n_171,r_171,n_172,...,r_194,r_195,n_196,r_196,r_197,r_198,r_199,n_175,r_175,label
222516,32329,20190108,4.294967e+09,97.0,0.0,37939.0,0.0,0.0,0.0,0.0,...,14.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.580052e+11,0
230228,32329,20190109,4.294967e+09,97.0,0.0,37963.0,0.0,0.0,0.0,0.0,...,15.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.580992e+11,1
277089,32329,20190110,4.294967e+09,97.0,0.0,37987.0,0.0,0.0,0.0,0.0,...,15.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.581931e+11,1
292292,32329,20190111,4.294967e+09,97.0,0.0,38011.0,0.0,0.0,0.0,0.0,...,15.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.582870e+11,1
324171,32329,20190112,4.294967e+09,97.0,0.0,38035.0,0.0,0.0,0.0,0.0,...,14.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.583809e+11,1
351731,32329,20190113,4.294967e+09,97.0,0.0,38058.0,0.0,0.0,0.0,0.0,...,14.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.621092e+11,1
380021,32329,20190114,4.294967e+09,97.0,0.0,38082.0,0.0,0.0,0.0,0.0,...,15.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.622030e+11,1
413548,32329,20190115,4.294967e+09,97.0,0.0,38106.0,0.0,0.0,0.0,0.0,...,15.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.622969e+11,1
435977,32329,20190116,4.294967e+09,97.0,0.0,38130.0,0.0,0.0,0.0,0.0,...,14.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.623909e+11,1
447314,32329,20190117,4.294967e+09,97.0,0.0,38154.0,0.0,0.0,0.0,0.0,...,15.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.624848e+11,1
482955,32329,20190118,4.294967e+09,97.0,0.0,38178.0,0.0,0.0,0.0,0.0,...,15.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.625787e+11,1
521770,32329,20190119,4.294967e+09,97.0,0.0,38202.0,0.0,0.0,0.0,0.0,...,15.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.626726e+11,1
540827,32329,20190120,4.294967e+09,97.0,0.0,38226.0,0.0,0.0,0.0,0.0,...,15.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.664009e+11,1
575552,32329,20190121,4.294967e+09,97.0,0.0,38250.0,0.0,0.0,0.0,0.0,...,14.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.664950e+11,1
594343,32329,20190122,4.294967e+09,97.0,0.0,38273.0,0.0,0.0,0.0,0.0,...,14.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.665889e+11,1
625732,32329,20190123,4.294967e+09,97.0,0.0,38297.0,0.0,0.0,0.0,0.0,...,14.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.666828e+11,1
652952,32329,20190124,4.294967e+09,97.0,0.0,38321.0,0.0,0.0,0.0,0.0,...,14.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.667767e+11,1
669171,32329,20190125,4.294967e+09,97.0,0.0,38345.0,0.0,0.0,0.0,0.0,...,13.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.668706e+11,1
716075,32329,20190126,4.294967e+09,97.0,0.0,38369.0,0.0,0.0,0.0,0.0,...,14.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.669645e+11,1
742192,32329,20190127,4.294967e+09,97.0,0.0,38393.0,0.0,0.0,0.0,0.0,...,14.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.706928e+11,1
771685,32329,20190128,4.294967e+09,97.0,0.0,38417.0,0.0,0.0,0.0,0.0,...,14.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.707867e+11,1
802734,32329,20190129,4.294967e+09,97.0,0.0,38441.0,0.0,0.0,0.0,0.0,...,15.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.708806e+11,1
822715,32329,20190130,4.294967e+09,97.0,0.0,38465.0,0.0,0.0,0.0,0.0,...,15.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.709745e+11,1
844144,32329,20190131,4.294967e+09,97.0,0.0,38488.0,0.0,0.0,0.0,0.0,...,14.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.710684e+11,1
869709,32329,20190201,4.294967e+09,97.0,0.0,38512.0,0.0,0.0,0.0,0.0,...,15.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.711623e+11,1
913303,32329,20190202,4.294967e+09,97.0,0.0,38536.0,0.0,0.0,0.0,0.0,...,15.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.712562e+11,1
918350,32329,20190203,4.294967e+09,97.0,0.0,38560.0,0.0,0.0,0.0,0.0,...,15.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.749846e+11,1
948227,32329,20190204,4.294967e+09,97.0,0.0,38584.0,0.0,0.0,0.0,0.0,...,15.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.750785e+11,1
997543,32329,20190205,4.294967e+09,97.0,0.0,38608.0,0.0,0.0,0.0,0.0,...,15.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.751724e+11,1
1017831,32329,20190206,4.294967e+09,97.0,0.0,38632.0,0.0,0.0,0.0,0.0,...,15.0,0.0,100.0,0.0,0.0,0.0,0.0,100.0,9.752663e+11,1

In [10]:
# label이 1인 행의 인덱스 찾기
label_indices = extracted_disk_failure_model_all[extracted_disk_failure_model_all['label'] == 1].index

# 변경된 값을 적용할 데이터프레임 복사
df_updated = extracted_disk_failure_model_all.copy()

# label이 1인 행을 기준으로 위의 29개 행의 label을 1로 변경
for idx in label_indices:
    start_index = max(idx - 29, 0)
    end_index = idx + 1

    # start_index가 음수인 경우 처리
    if start_index < 0:
        rows_to_label = extracted_disk_failure_model_all.iloc[:end_index]
    else:
        rows_to_label = extracted_disk_failure_model_all.iloc[start_index:end_index]

    # disk_id가 변경된 행이 있는 경우 해당 행을 제외하고 label을 1로 변경
    disk_id_changed_index = rows_to_label[rows_to_label['disk_id'].diff() != 0].index
    rows_to_label.loc[~rows_to_label.index.isin(disk_id_changed_index), 'label'] = 1

    # 변경된 값을 원본 데이터프레임에 적용
    df_updated.update(rows_to_label)

In [12]:
df_updated['label'].value_counts()

label
0    27399
1     7816
Name: count, dtype: int64

In [19]:
df_updated[df_updated['disk_id'] == 42824]

,disk_id,ds,r_1,n_5,r_5,r_9,r_12,n_171,r_171,n_172,...,r_194,r_195,n_196,r_196,r_197,r_198,r_199,n_175,r_175,label
35037,42824,20190101,4.294967e+09,94.0,0.0,44656.0,46.0,100.0,0.0,100.0,...,18.0,871381782.0,100.0,0.0,0.0,0.0,0.0,100.0,1.134079e+12,0
35038,42824,20190102,4.294967e+09,94.0,0.0,44680.0,46.0,100.0,0.0,100.0,...,18.0,871540159.0,100.0,0.0,0.0,0.0,0.0,100.0,1.134173e+12,1
35039,42824,20190103,4.294967e+09,94.0,0.0,44704.0,46.0,100.0,0.0,100.0,...,18.0,871700155.0,100.0,0.0,0.0,0.0,0.0,100.0,1.134267e+12,1
35040,42824,20190104,4.294967e+09,94.0,0.0,44728.0,46.0,100.0,0.0,100.0,...,18.0,871852493.0,100.0,0.0,0.0,0.0,0.0,100.0,1.134361e+12,1
35041,42824,20190105,4.294967e+09,94.0,0.0,44751.0,46.0,100.0,0.0,100.0,...,18.0,872001710.0,100.0,0.0,0.0,0.0,0.0,100.0,1.134455e+12,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35210,42824,20190626,4.294967e+09,94.0,0.0,48860.0,46.0,100.0,0.0,100.0,...,17.0,884843672.0,100.0,0.0,0.0,0.0,0.0,100.0,1.241470e+12,0
35211,42824,20190627,4.294967e+09,94.0,0.0,48884.0,46.0,100.0,0.0,100.0,...,17.0,884886553.0,100.0,0.0,0.0,0.0,0.0,100.0,1.241564e+12,0
35212,42824,20190628,4.294967e+09,94.0,0.0,48908.0,46.0,100.0,0.0,100.0,...,18.0,884924703.0,100.0,0.0,0.0,0.0,0.0,100.0,1.241658e+12,0
35213,42824,20190629,4.294967e+09,94.0,0.0,48932.0,46.0,100.0,0.0,100.0,...,18.0,884965991.0,100.0,0.0,0.0,0.0,0.0,100.0,1.241751e+12,0
35214,42824,20190630,4.294967e+09,94.0,0.0,48955.0,46.0,100.0,0.0,100.0,...,18.0,885006704.0,100.0,0.0,0.0,0.0,0.0,100.0,1.241845e+12,0

In [16]:
label_indices

Index([3525699, 1621336, 3824021, 2774829, 4175174,  460817,  470965,  449329,
        453156,  467181,
       ...
         70405, 3526764, 3587876, 2753214, 3476772, 1627577, 3429526, 3213228,
       1760506,  302808],
      dtype='int64', length=304)

In [ ]:
MA1 = MA1.sort_values(['disk_id', 'ds'])

In [23]:


# label이 1인 행의 인덱스 찾기
label_indices = extracted_disk_failure_model_all[extracted_disk_failure_model_all['label'] == 1].index

# 변경된 값을 적용할 데이터프레임 복사
df_updated = extracted_disk_failure_model_all.copy()

# label이 1인 행을 기준으로 위의 29개 행의 label을 1로 변경
for idx in label_indices:
    start_index = max(idx - 29, 0)
    end_index = idx + 1

    # start_index가 음수인 경우 처리
    if start_index < 0:
        rows_to_label = extracted_disk_failure_model_all.iloc[:end_index]
    else:
        rows_to_label = extracted_disk_failure_model_all.iloc[start_index:end_index]

    # disk_id가 변경된 행이 있는 경우 해당 행을 제외하고 label을 1로 변경
    disk_id_changed_index = rows_to_label[rows_to_label['disk_id'].diff() != 0].index
    rows_to_label.loc[~rows_to_label.index.isin(disk_id_changed_index), 'label'] = 1

    # 변경된 값을 원본 데이터프레임에 직접 대입하여 업데이트
    df_updated.iloc[start_index:end_index] = rows_to_label

df_updated = df_updated.sort_index()  # 인덱스 순서로 정렬된 데이터프레임

print(df_updated)

       disk_id        ds           r_1   n_5  r_5      r_9  r_12  n_171  \
0          520  20190130  9.376596e+08  96.0  0.0  38191.0  27.0  100.0
1          520  20190131  1.624577e+09  96.0  0.0  38215.0  27.0  100.0
2          520  20190201  2.014090e+09  96.0  0.0  38239.0  27.0  100.0
3          520  20190202  2.812968e+09  96.0  0.0  38263.0  27.0  100.0
4          520  20190203  3.442008e+09  96.0  0.0  38287.0  27.0  100.0
...        ...       ...           ...   ...  ...      ...   ...    ...
35210    42824  20190626  4.294967e+09  94.0  0.0  48860.0  46.0  100.0
35211    42824  20190627  4.294967e+09  94.0  0.0  48884.0  46.0  100.0
35212    42824  20190628  4.294967e+09  94.0  0.0  48908.0  46.0  100.0
35213    42824  20190629  4.294967e+09  94.0  0.0  48932.0  46.0  100.0
35214    42824  20190630  4.294967e+09  94.0  0.0  48955.0  46.0  100.0

       r_171  n_172  ...  r_194        r_195  n_196  r_196  r_197  r_198  \
0        0.0  100.0  ...   16.0   33733630.0  100.0    0.0    0.0    0.0
1        0.0  100.0  ...   17.0   33733726.0  100.0    0.0    0.0    0.0
2        0.0  100.0  ...   17.0   33733759.0  100.0    0.0    0.0    0.0
3        0.0  100.0  ...   16.0   33733774.0  100.0    0.0    0.0    0.0
4        0.0  100.0  ...   15.0   33733798.0  100.0    0.0    0.0    0.0
...      ...    ...  ...    ...          ...    ...    ...    ...    ...
35210    0.0  100.0  ...   17.0  884843672.0  100.0    0.0    0.0    0.0
35211    0.0  100.0  ...   17.0  884886553.0  100.0    0.0    0.0    0.0
35212    0.0  100.0  ...   18.0  884924703.0  100.0    0.0    0.0    0.0
35213    0.0  100.0  ...   18.0  884965991.0  100.0    0.0    0.0    0.0
35214    0.0  100.0  ...   18.0  885006704.0  100.0    0.0    0.0    0.0

       r_199  n_175         r_175  label
0        0.0  100.0  9.793172e+11      0
1        0.0  100.0  9.794111e+11      0
2        0.0  100.0  9.795051e+11      0
3        0.0  100.0  9.795990e+11      0
4        0.0  100.0  9.796929e+11      0
...      ...    ...           ...    ...
35210    0.0  100.0  1.241470e+12      0
35211    0.0  100.0  1.241564e+12      0
35212    0.0  100.0  1.241658e+12      0
35213    0.0  100.0  1.241751e+12      0
35214    0.0  100.0  1.241845e+12      0

[35215 rows x 31 columns]

In [24]:
df_updated['label'].value_counts()

label
0    27399
1     7816
Name: count, dtype: int64